### ISSUE TITLE
开启API时提示错误

### ISSUE THREAD

**Issue by japssss019** [fishaudio/fish-speech#468]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled 
我已经安装好了CUDA和TORCH环境以及变量，此问题只在开启API时出现

**Comment by AnyaCoder** [comment]
发一下配置以及环境的详细信息。包括OS、python version, torch version等，还有你的命令

**Comment by japssss019** [comment]
Windows 11 22H2
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
torch                     2.4.0+cu121
torchaudio                2.4.0
torchmetrics              1.4.1
torchvision               0.19.0
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

已按照要求编辑项目根目录下的 API_FLAGS.txt, 前三行修改成如下格式:
# --infer
--api
--listen ...
...后，运行start.bat
提示如下
![QQ截图20240814141757](https://github.com/user-attachments/assets/c9ad4060-affa-4fc4-b4f7-21e93c7140c9)

**Comment by Stardust-minus** [comment]
torch装呲了，换2.3.1+c121

**Comment by japssss019** [comment]
收到，我去装个2.3.1的试试

**Comment by AnyaCoder** [comment]
这么看来， 你用的是`INSTALL_TYPE=stable`装的吧？
文档可能得暂时改一下。

**Comment by japssss019** [comment]
已经解决了，主要还是TORCH版本的问题，感谢各位的帮助
